// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.math.geometry.Translation3d;
import swervelib.math.Matter;
import edu.wpi.first.math.util.Units;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
  /**
   * public static final class DriveConstants {
   * public static final int kLeftMotor1Port = 0;
   * public static final int kLeftMotor2Port = 1;
   * public static final int kRightMotor1Port = 2;
   * public static final int kRightMotor2Port = 3;
   * }
   */

  public static final double ROBOT_MASS = (148 - 20.3) * 0.453592; // 32lbs * kg per pound
  public static final Matter CHASSIS = new Matter(new Translation3d(0, 0, Units.inchesToMeters(8)), ROBOT_MASS);
  public static final double LOOP_TIME = 0.13; // s, 20ms + 110ms sprk max velocity lag
  public static final double MAX_SPEED = Units.feetToMeters(15.39); // need to update

  public static final class DrivebaseConstants {

    // Hold time on motor brakes when disabled
    public static final double WHEEL_LOCK_TIME = 10; // seconds
  }

  public static class OperatorConstants {

    // Joystick Deadband
    public static final double DEADBAND = 0.01;
    public static final double LEFT_Y_DEADBAND = 0.01;
    public static final double RIGHT_X_DEADBAND = 0.01;
    public static final double TURN_CONSTANT = 6;
  }

  public static final class VisionConstants{
    public static final  double maximumAmbiguity = 0.25;
    public static final double debouncetimeMilli = 15;

   /*  public static final class CameraTemplate{
      public static final String name = "tempalte"; // tempalte?
      public static  Rotation3d robotToCamTransform = new Rotation3d(0, Units.degreesToRadians(18), 0);
      public static  Translation3d robotToCamTranslation=new Translation3d(Units.inchesToMeters(-4.628),
      Units.inchesToMeters(-10.687),
      Units.inchesToMeters(16.129));
      public static  Matrix<N3, N1> singleTagStdDevs= VecBuilder.fill(2, 2, 8);
      public static  Matrix<N3, N1> multiTagStdDevsMatrix= VecBuilder.fill(0.5, 0.5, 1); 
    }

    public static final class RIGHT_CAM{
      public static final String name = "right";
      public static  Rotation3d robotToCamTransform = new Rotation3d(0, 0, Units.degreesToRadians(-45));
      public static  Translation3d robotToCamTranslation=new Translation3d(Units.inchesToMeters(0),
      Units.inchesToMeters(0),
      Units.inchesToMeters(0));
      public static  Matrix<N3, N1> singleTagStdDevs= VecBuilder.fill(4, 4, 8);
      public static  Matrix<N3, N1> multiTagStdDevsMatrix= VecBuilder.fill(0.5, 0.5, 1); 
      public static InterpolatingDoubleTreeMap stdDevsMap = new InterpolatingDoubleTreeMap();
    }
  */
    

    public static final double leftAlignmentX = .2435737274077523; //meters
    public static final double leftAlignmentY = 0.26;
    public static final double rightAlignmentX = .2435737274077523;
    public static final double rightAlignmentY = 0.6354460866293814;
    public static final double thetaAlignment = -Math.PI/2; //degrees
    public static double maxAlignmentDistance = 1.5;

    public static final double xTolerance = .05;
    public static final double yTolerance = .05;
    public static final double thetaTolerance = .05;
  }

  public static class SwerveConstants {
    public static final double kPX = 1.5;
    public static final double kPY = 1.25;
    public static final double kPTheta = 0.08;
    public static final double kXTolerance = 0.00; //Meters
    public static final double kYTolerance = 0.00; //Meters
    public static final double kThetaTolerance = 0;
    public static double kStoredRadius = 3.9527559/2; // to be configured later
    public static double kDrivebaseRadius = .409;
  }

  public enum MOTORS {
        TOWER1_MOTOR_RIGHT("Tower 1 Motor Right", "Flywheels", 9),
        TOWER1_MOTOR_LEFT("Tower 1 Motor Left", "Flywheels", 10),
        TOWER2_MOTOR_RIGHT("Tower 2 Motor Right", "Flywheels", 11),
        TOWER2_MOTOR_LEFT("Tower 2 Motor Left", "Flywheels", 12),
        FEEDER_MOTOR("Feeder Motor", "Hopper", 13),
        INTAKE_MOTOR("Intake Motor", "Intake", 14),
        CLIMBER_MOTOR("Climber Motor", "Climb", 15),
        FUNNEL_MOTOR("Funnel Motor", "Hopper", 16),
        EXTEND_MOTOR("Extend Motor", "Intake", 17),
        RCLIMB_MOTOR("Right Climb Motor", "Climb", 18),
        LCLIMB_MOTOR("Left Climb Motor", "Climb", 19),
        TURN_MOTOR("Turret Turn Motor", "LTurret", 20);

        public final String motorName;
        public final String subSystem;
        public final int canId;

        MOTORS(String motorName, String subSystem, int canId) {
            this.motorName = motorName;
            this.subSystem = subSystem;
            this.canId = canId;
        }
    }


}