// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.Constants.OperatorConstants;
import frc.robot.commands.*;
import frc.robot.subsystems.*;
import frc.robot.subsystems.ElevatorAndArm.ElevAndArmPos;
import swervelib.SwerveInputStream;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;

import java.io.File;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathPlannerAuto;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import frc.robot.subsystems.*;
import frc.robot.commands.drivebase.AbsoluteDriveAdv;

import frc.robot.commands.*;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in
 * the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of
 * the robot
 * (including subsystems, commands, and button mappings) should be declared
 * here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  // The robot's subsystems
  public final Sensors m_sensors = new Sensors();
  public final DriveTrain m_driveTrain = new DriveTrain(new File(Filesystem.getDeployDirectory(), "swerve"));
  public final ElevatorAndArm m_elevatorAndArm = new ElevatorAndArm();
  // Joysticks
  private final CommandXboxController Articulator = new CommandXboxController(1);
  private final CommandXboxController drive_Controller = new CommandXboxController(0);

  private final SendableChooser<Command> autoChooser;
  
  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  /**
   * Converts driver input into a field-relative ChassisSpeeds that is controlled
   * by angular velocity.
   */
  SwerveInputStream driveAngularVelocity = SwerveInputStream.of(m_driveTrain.getSwerveDrive(),
      () -> drive_Controller.getLeftY() * -1,
      () -> drive_Controller.getLeftX() * -1)
      .withControllerRotationAxis(this::getRightXInverted)
      .deadband(OperatorConstants.DEADBAND)
      .scaleTranslation(0.8)
      .allianceRelativeControl(true);

  // Applies deadbands and inverts controls because joysticks
  // are back-right positive while robot
  // controls are front-left positive
  // left stick controls translation
  // right stick controls the desired angle NOT angular rotation
  Command driveFieldOrientedDirectAngle = m_driveTrain.driveFieldOriented(driveAngularVelocity);

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  private double getRightXInverted() {
    return this.drive_Controller.getRightX() * -1;

  }

  /**
   * The container for the robot. Contains subsystems, OI devices, and commands.
   */
  private RobotContainer() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems
    autoChooser = AutoBuilder.buildAutoChooser();

    // SmartDashboard Buttons
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("Elevator TO Level 1", new EAGoToLevel(ElevAndArmPos.LEVEL1));
    SmartDashboard.putData("Elevator TO Level 2", new EAGoToLevel(ElevAndArmPos.LEVEL2));
    SmartDashboard.putData("Elevator TO Level 3", new EAGoToLevel(ElevAndArmPos.LEVEL3));
    SmartDashboard.putData("Elevator TO Level 4", new EAGoToLevel(ElevAndArmPos.LEVEL4));
    SmartDashboard.putData("Pickup", new EAGoToLevel(ElevAndArmPos.PICKUP));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    m_chooser.setDefaultOption("Level1", new EAGoToLevel(ElevAndArmPos.LEVEL1));
    m_chooser.addOption("Level2", new EAGoToLevel(ElevAndArmPos.LEVEL2));
    m_chooser.addOption("Level3", new EAGoToLevel(ElevAndArmPos.LEVEL3));
    m_chooser.addOption("Level4", new EAGoToLevel(ElevAndArmPos.LEVEL4));
    m_chooser.addOption("OutOfWay", new EAGoToLevel(ElevAndArmPos.OUTOFWAY));
    m_chooser.addOption("Safety", new EAGoToLevel(ElevAndArmPos.SAFETYPOS));
    m_chooser.addOption("Pickup", new EAGoToLevel(ElevAndArmPos.PICKUP));

    autoChooser.setDefaultOption("Test Path", new PathPlannerAuto("Test Drive Straight.auto"));
    autoChooser.addOption("Test Path", new PathPlannerAuto("Test Drive Straight.auto"));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", autoChooser);
    SmartDashboard.putData("Elevator test", m_chooser);
   // SmartDashboard.putData("run test command", m_chooser.getSelected().schedule());
    
  }
  public void updateDashboard() {
   SmartDashboard.putNumber("elevatorPos", m_elevatorAndArm.getElevatorCurPos());
   SmartDashboard.putNumber("elevatorVelocity", m_elevatorAndArm.getElevatorVelocity());
   //add current odometry position to smartdashboard
SmartDashboard.putNumber("Robot X Position", m_driveTrain.getPose().getX());
SmartDashboard.putNumber("Robot Y Position", m_driveTrain.getPose().getY());
SmartDashboard.putNumber("Robot Rotation", m_driveTrain.getPose().getRotation().getDegrees());
   //add vision data to smartdashboard
   
  }
  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be
   * created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing
   * it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
    // Create some buttons
    m_driveTrain.setDefaultCommand(driveFieldOrientedDirectAngle);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
  public CommandXboxController getDrive_Controller() {
    return drive_Controller;
  }

  public CommandXboxController getArticulator() {
    return Articulator;
  }

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command runTestCommand() {
    
     return m_chooser.getSelected();
  }

}
